local acp = require('tark.acp_client')

describe('acp client', function()
    it('exposes required ACP API functions', function()
        assert.is_function(acp.setup)
        assert.is_function(acp.on)
        assert.is_function(acp.ensure_started)
        assert.is_function(acp.send_message)
        assert.is_function(acp.inline_completion)
        assert.is_function(acp.set_mode)
        assert.is_function(acp.cancel)
        assert.is_function(acp.queue_size)
        assert.is_function(acp.is_connected)
        assert.is_function(acp.close)
    end)

    it('starts with empty queue', function()
        assert.equals(0, acp.queue_size())
    end)
end)
