local context = require('tark.widgets.context')

describe('context capture', function()
    it('captures current buffer metadata', function()
        vim.cmd('enew')
        vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'line one', 'line two' })
        vim.api.nvim_win_set_cursor(0, { 2, 3 })

        local ctx = context.from_current_buffer()
        assert.is_table(ctx)
        assert.is_table(ctx.cursor)
        assert.equals(2, ctx.cursor.line)
        assert.equals(4, ctx.cursor.col)
        assert.is_table(ctx.buffers)
    end)

    it('captures visual selection with line and column range', function()
        vim.cmd('enew')
        vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'alpha beta', 'gamma delta' })
        vim.api.nvim_buf_set_mark(0, '<', 1, 0, {})
        vim.api.nvim_buf_set_mark(0, '>', 1, 4, {})

        local ctx = context.from_visual_selection(1, 1)
        assert.is_table(ctx.selection)
        assert.equals(1, ctx.selection.start_line)
        assert.equals(1, ctx.selection.start_col)
        assert.equals(1, ctx.selection.end_line)
        assert.equals(5, ctx.selection.end_col)
    end)

    it('avoids using tark widget buffer as active file context', function()
        vim.cmd('enew')
        local code_buf = vim.api.nvim_get_current_buf()
        vim.api.nvim_buf_set_name(code_buf, vim.fn.getcwd() .. '/sample.lua')
        vim.api.nvim_buf_set_lines(code_buf, 0, -1, false, { 'print(\"hello\")' })

        vim.cmd('vsplit')
        local widget_buf = vim.api.nvim_create_buf(false, true)
        vim.api.nvim_buf_set_name(widget_buf, 'tark://chat/input')
        vim.api.nvim_win_set_buf(0, widget_buf)

        local ctx = context.from_current_buffer()
        assert.is_true((ctx.active_file or ''):match('sample%.lua') ~= nil)
    end)
end)
