local ghost = require('tark.ghost')

describe('ghost - ACP inline completion', function()
    describe('module functions exist', function()
        it('has enable/disable/toggle', function()
            assert.is_function(ghost.enable)
            assert.is_function(ghost.disable)
            assert.is_function(ghost.toggle)
        end)

        it('has request lifecycle helpers', function()
            assert.is_function(ghost.trigger)
            assert.is_function(ghost.accept)
            assert.is_function(ghost.dismiss)
        end)

        it('has setup and UI wiring functions', function()
            assert.is_function(ghost.setup)
            assert.is_function(ghost.setup_autocmds)
            assert.is_function(ghost.setup_keymaps)
        end)
    end)

    describe('state tracking', function()
        it('tracks active request sequence', function()
            assert.is_number(ghost.state.request_seq)
            assert.is_number(ghost.state.active_request_seq)
        end)

        it('tracks usage counters', function()
            assert.is_number(ghost.state.completions_requested)
            assert.is_number(ghost.state.completions_shown)
            assert.is_number(ghost.state.completions_accepted)
        end)
    end)

    describe('config', function()
        it('has ACP-first defaults', function()
            assert.is_table(ghost.config)
            assert.is_boolean(ghost.config.enabled)
            assert.is_boolean(ghost.config.auto_trigger)
            assert.is_number(ghost.config.debounce_ms)
            assert.is_string(ghost.config.accept_key)
            assert.is_string(ghost.config.hl_group)
        end)
    end)

    describe('usage/status output', function()
        it('returns usage table', function()
            local stats = ghost.usage()
            assert.is_table(stats)
            assert.is_boolean(stats.enabled)
            assert.is_boolean(stats.acp_connected)
            assert.is_number(stats.completions_requested)
        end)

        it('returns formatted usage text', function()
            local output = ghost.format_usage()
            assert.is_string(output)
            assert.is_true(output:match('Ghost Text Stats') ~= nil)
        end)

        it('returns ACP status text', function()
            local output = ghost.status()
            assert.is_string(output)
            assert.is_true(output:match('ACP') ~= nil)
        end)
    end)

    describe('safe no-op behavior', function()
        it('dismiss clears suggestion', function()
            ghost.dismiss()
            assert.is_nil(ghost.state.current_suggestion)
        end)

        it('disable can be called repeatedly', function()
            assert.has_no_errors(function()
                ghost.disable()
                ghost.disable()
            end)
        end)

        it('setup merges config', function()
            ghost.setup({ debounce_ms = 500 })
            assert.equals(500, ghost.config.debounce_ms)
            ghost.setup({ debounce_ms = 300 })
        end)
    end)
end)
