local chat = require('tark.widgets.chat')

describe('questionnaire APIs removed in strict ACP cutover', function()
    it('does not expose legacy questionnaire methods', function()
        assert.is_nil(chat.on_questionnaire_request)
        assert.is_nil(chat.pending_questionnaire)
        assert.is_nil(chat.questionnaire_answers)
        assert.is_nil(chat.can_submit_questionnaire)
        assert.is_nil(chat.clear_pending_questionnaire)
    end)
end)
